// .catch(errorFunction(error))
        // this fetch needs a catch.  catch catches errors that can then be handled(usually with a message). you need an if statement inside catch that says if errors > 2, alert to user a message telling them to give up.  define errors (=0), outside of catch. 
        // 
        // function errorFunction(){
        //     if(errors > )
        // }